### ISSUE TITLE
GUI Application must gather needed information

### ISSUE THREAD

**Issue by tmfulton** [UMLGenerator/Android-UML-Generator#8]
On the click of start, the GUI application must get the package name of the selected application, and then parse through the application, searching for all classes and methods in it. This information should then be written to a file on the phone

**Comment by mformetal** [comment]
"searching for all classes and methods in it. This information should then be written to a file on the phone" 

Just for clarification, this task is relegated to the xposed module, right? Because, if so, this should be in two separate issues. 1) GUI gets package name of application, writes to file, and 2) Xposed gets that package name, parses it for classes/ methods. 

This functionality is in the latest commit of my GUI branch. Won't close until we review it.

**Comment by mformetal** [comment]
Gonna go ahead and close this issue, the GUI branch (specifically this commit https://github.com/tmfulton/Android-UML-Generator/tree/f26521e9420d4be032c2e4a1a872ac0c945c7c2e) accomplishes this functionality.
